package config

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

var inited = false
var privateKey ed25519.PrivateKey
var publicKey ed25519.PublicKey

var DB *pgxpool.Pool

var JWTAccessTokenDuration = time.Minute * 15     // Access token: 15 minutes
var JWTRefreshTokenDuration = time.Hour * 24 * 30 // Refresh token: 1 month

const DatabaseUrl = "postgres://postgres:ztsubaki@localhost:5432/test"

func InitDB() (*pgxpool.Pool, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, DatabaseUrl)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	if err := pool.Ping(ctx); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	DB = pool
	log.Println("Connected to PostgreSQL")

	// Auto-create tables if they don't exist
	if err := autoMigrate(ctx, pool); err != nil {
		return nil, fmt.Errorf("failed to auto-migrate database: %w", err)
	}

	return pool, nil
}

// autoMigrate creates tables if they don't exist
func autoMigrate(ctx context.Context, pool *pgxpool.Pool) error {
	// Create users table
	_, err := pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS users (
			uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			username VARCHAR(15) UNIQUE NOT NULL,
			password VARCHAR(64) NOT NULL,
			salt VARCHAR(16) NOT NULL,
			login_salt VARCHAR(16),
			email VARCHAR(255) UNIQUE,
			nickname VARCHAR(50),
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Create sessions table for token management
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS sessions (
			session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			uid BIGINT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			jti CHAR(32)
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create sessions table: %w", err)
	}

	// Create indexes
	_, err = pool.Exec(ctx, `CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)`)
	if err != nil {
		return fmt.Errorf("failed to create idx_users_username: %w", err)
	}

	_, err = pool.Exec(ctx, `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`)
	if err != nil {
		return fmt.Errorf("failed to create idx_users_email: %w", err)
	}

	_, err = pool.Exec(ctx, `CREATE INDEX IF NOT EXISTS idx_sessions_uid ON sessions(uid)`)
	if err != nil {
		return fmt.Errorf("failed to create idx_sessions_uid: %w", err)
	}

	_, err = pool.Exec(ctx, `CREATE INDEX IF NOT EXISTS idx_sessions_jti ON sessions(jti)`)
	if err != nil {
		return fmt.Errorf("failed to create idx_sessions_jti: %w", err)
	}

	// Create contests table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS contests (
			contest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL,
			description TEXT,
			start_time TIMESTAMP NOT NULL,
			end_time TIMESTAMP NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create contests table: %w", err)
	}

	// Create problems table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS problems (
			problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(100) NOT NULL,
			description TEXT,
			input_format TEXT,
			output_format TEXT,
			sample_input TEXT,
			sample_output TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create problems table: %w", err)
	}

	// Create submissions table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS submissions (
			submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			problem_id BIGINT NOT NULL REFERENCES problems(problem_id) ON DELETE CASCADE,
			contest_id BIGINT REFERENCES contests(contest_id) ON DELETE CASCADE,
			uid BIGINT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
			code TEXT NOT NULL,
			language VARCHAR(20) NOT NULL,
			status VARCHAR(20) DEFAULT 'Pending',
			submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create submissions table: %w", err)
	}

	// Create contest_participants table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS contest_participants (
			contest_id BIGINT NOT NULL REFERENCES contests(contest_id) ON DELETE CASCADE,
			uid BIGINT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
			joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (contest_id, uid)
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create contest_participants table: %w", err)
	}

	// Create contest_problems table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS contest_problems (
			contest_id BIGINT NOT NULL REFERENCES contests(contest_id) ON DELETE CASCADE,
			problem_id BIGINT NOT NULL REFERENCES problems(problem_id) ON DELETE CASCADE,
			PRIMARY KEY (contest_id, problem_id)
		)
	`)
	if err != nil {
		return fmt.Errorf("failed to create contest_problems table: %w", err)
	}

	log.Println("Database auto-migration completed")
	return nil
}

func CloseDB() {
	if DB != nil {
		DB.Close()
	}
}

func JWTPrivateKey() ed25519.PrivateKey {
	ensureInit()
	return privateKey
}

func JWTPublicKey() ed25519.PublicKey {
	ensureInit()
	return publicKey
}

func ensureInit() {
	if inited {
		return
	}

	// Try to load keys from environment variable (base64 encoded)
	// Format: PRIVATE_KEY_HEX or PRIVATE_KEY_BASE64
	privateKeyHex := os.Getenv("JWT_PRIVATE_KEY_HEX")
	if privateKeyHex != "" {
		privateKeyBytes, err := hex.DecodeString(privateKeyHex)
		if err == nil && len(privateKeyBytes) == ed25519.PrivateKeySize {
			privateKey = ed25519.PrivateKey(privateKeyBytes)
			publicKey = privateKey.Public().(ed25519.PublicKey)
			inited = true
			log.Println("Loaded JWT keys from environment variable")
			return
		}
	}

	// Generate new keys (for development only - tokens will be invalid after restart)
	pubKey, priKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		panic(err)
	}
	privateKey = priKey
	publicKey = pubKey
	inited = true
	log.Println("Generated new JWT keys (development mode - keys not persisted)")
	log.Printf("Set JWT_PRIVATE_KEY_HEX environment variable to persist keys: %s\n", hex.EncodeToString(privateKey))
}
